@startuml
!include ./include/C4_Context.puml

title C4 Level 1 – System Context

Person(user, "Пользователь")
Person(admin, "Администратор ФК")

System_Boundary(lk, "Подсистема автонастройки АРМ") {

    System(master, "Master AutoSetup", "Avalonia .NET", "Проводит диагностику и автоматическую настройку АРМ")

    System(grav, "CMS Grav", "PHP CMS", "Отображение портала входа, новости, аварийные сообщения, ссылки на мастера")

    System(eb, "ЛК ГИИС «Электронный бюджет»", "Web System", "Целевая система после настройки АРМ")
}

Rel(user, grav, "Открывает портал, скачивает мастер", "HTTP/HTTPS")
Rel(user, master, "Запускает мастер локально")
Rel(admin, grav, "Управляет контентом", "HTTPS (локальная сеть)")
Rel(master, eb, "Открывает ЛК ЭБ", "HTTPS")

@enduml